approve:
- lgtm_acts_as_approve: true
  repos:
  - linuxsuren
  - jenkinsci
  - jenkins-zh
  - jenkins-infra
  - devops-ws
  require_self_approval: false
cat: {}
cherry_pick_unapproved: {}
config_updater:
  gzip: false
  maps:
    plugins.yaml:
      name: plugins
      namespace: default
    config.yaml:
      name: config
      namespace: default
    labels.yaml:
      name: label-config
      namespace: default
external_plugins: {}
heart: {}
label:
  additional_labels:
    - article
    - translation
    - tutorial
owners: {}
plugins:
  jenkins-infra:
    - approve
    - assign
    - cat
    - dog
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks
    - welcome
  jenkinsci:
    - approve
    - assign
    - cat
    - dog
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks
    - welcome
  jenkins-zh:
    - approve
    - assign
    - cat
    - dog
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks
    - welcome
  LinuxSuRen/linuxsuren-bot-config:
    - config-updater
  linuxsuren:
    - approve
    - assign
    - cat
    - dog
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks
    - welcome
  devops-ws:
    - approve
    - assign
    - cat
    - dog
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks
    - welcome
requiresig: {}
sigmention: {}
size:
  xs: 10
  s: 20
  m: 40
  l: 80
  xl: 160
  xxl: 320
triggers: []
welcome:
  - message_template: "欢迎 @{{.AuthorLogin}} 加入，这是您首次参与 Jenkins 中文社区的开源贡献，让我们共同见证开源社区的成长！"
    repos:
    - jenkins-zh/jenkins-zh
  - message_template: "欢迎 @{{.AuthorLogin}} 和我们一起总结、完善开源最佳实践！"
    repos:
    - LinuxSuRen/open-source-best-practice
