approve:
- lgtm_acts_as_approve: true
  repos:
  - linuxsuren
  - jenkinsci
  - jenkins-zh
  - jenkins-infra
  require_self_approval: false
cat: {}
cherry_pick_unapproved: {}
config_updater:
  gzip: false
  maps:
    plugins.yaml:
      name: plugins
      namespace: default
    config.yaml:
      name: config
      namespace: default
external_plugins: {}
heart: {}
label:
  additional_labels:
    - article
    - translation
    - tutorial
owners: {}
plugins:
  jenkins-infra:
    - approve
    - assign
    - cat
    - dog
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks
    - welcome
  jenkinsci:
    - approve
    - assign
    - cat
    - dog
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks
    - welcome
  jenkins-zh:
    - approve
    - assign
    - cat
    - dog
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks
    - welcome
  LinuxSuRen/linuxsuren-bot-config:
    - config-updater
  linuxsuren:
    - approve
    - assign
    - cat
    - dog
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks
    - welcome
requiresig: {}
sigmention: {}
size:
  s: 10
  l: 30
  m: 50
  xl: 70
  xxl: 100
triggers: []
# Example triggers configuration:
# - repos:
#     - org/repo
#   trusted_org: org
welcome:
- message_template: Welcome
