apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - linuxsuren
      - jenkinsci
      - jenkins-zh
      - jenkins-infra
      require_self_approval: false
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps: {}
    external_plugins: {}
    heart: {}
    label:
      additional_labels:
        - article
        - translation
    owners: {}
    plugins:
      jenkins-infra:
        - approve
        - assign
        - cat
        - dog
        - help
        - hold
        - label
        - lgtm
        - lifecycle
        - override
        - pony
        - shrug
        - size
        - skip
        - trigger
        - wip
        - yuks
        - welcome
      jenkinsci:
        - approve
        - assign
        - cat
        - dog
        - help
        - hold
        - label
        - lgtm
        - lifecycle
        - override
        - pony
        - shrug
        - size
        - skip
        - trigger
        - wip
        - yuks
        - welcome
      jenkins-zh:
        - approve
        - assign
        - cat
        - dog
        - help
        - hold
        - label
        - lgtm
        - lifecycle
        - override
        - pony
        - shrug
        - size
        - skip
        - trigger
        - wip
        - yuks
        - welcome
      LinuxSuRen/linuxsuren-bot-config:
        - config-updater
        - approve
        - assign
        - cat
        - dog
        - help
        - hold
        - label
        - lgtm
        - lifecycle
        - override
        - pony
        - size
        - skip
        - trigger
        - wip
        - yuks
        - welcome
      linuxsuren:
        - approve
        - assign
        - cat
        - dog
        - help
        - hold
        - label
        - lgtm
        - lifecycle
        - override
        - pony
        - shrug
        - size
        - skip
        - trigger
        - wip
        - yuks
        - welcome
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers: []
    # Example triggers configuration:
    # - repos:
    #     - org/repo
    #   trusted_org: org
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: lighthouse
    meta.helm.sh/release-namespace: default
  labels:
    app: lighthouse-lighthouse
    app.kubernetes.io/managed-by: Helm
    chart: lighthouse-0.0.922
    release: lighthouse
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:release: {}
    manager: Go-http-client
    operation: Update
    time: "2021-01-30T15:09:52Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:plugins.yaml: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-02-02T12:51:39Z"
  name: plugins
  namespace: default
